filebeat.inputs:
  - type: log
    paths:
      - /logs/*.json
    json.keys_under_root: true
    json.add_error_key: true
    json.message_key: message

#processors:
#  - add_host_metadata: ~
#  - add_cloud_metadata: ~
#  - add_docker_metadata: ~
#  - add_kubernetes_metadata: ~

output.logstash:
  hosts: ["logstash:5044"]